### ISSUE TITLE
Create sign in and sign out  Activity.

### ISSUE THREAD

**Issue by Akshayp02** [TechHubsters/ShopNxtGen#1]
Create sign in and sign out  Activity under the app/src/main/java/com/example/shopnxtgen

**Comment by dharshinivenkatesan** [comment]
Hello! I'm excited about this project and would love to contribute. I understand that we'll be using Android Studio (Java), Google AI, Square API, and Firebase DB. I see the two user modules, Business owner and Customer, and plan to work on features like real-time sales insights, inventory management, predictive analytics, and a user-friendly UI. Let's collaborate and make this project a success!

**Comment by Akshayp02** [comment]
Ok i am assigning you
